version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: ukraine-news-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - ALERTS_API_TOKEN=${ALERTS_API_TOKEN}
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  logs:
  data:
